elastic:
  # Set local to true to use embedded Elasticsearch (for quick testing)
  local: false
  cluster: elasticsearch
  hosts: localhost

keycloak:
  realm: xxxxx
  auth-server-url: xxxx
  ssl-required: EXTERNAL
  resource: gbsp-webservice
  credentials:
    secret: xxxx
  use-resource-role-mappings: false
  bearer-only: true
  securityConstraints:
    - securityCollections:
      - name: spring secured api
        authRoles:
          - FULL_ACCESS
        patterns:
          - '/post/*'
          - '/account/*'